name: Build My Angular App

on:
  push:
    branches: [ main ]

jobs:
  build-angular-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0
      - name: Setup Node Js
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 22.x
      - name: Install Dependency
        run: npm install
      - name: Build Angular App
        run: npm run build
        
      
      
